name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # تغيير بيئة التشغيل إلى ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip build-essential git zip unzip openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer
          pip install cython  # تثبيت Cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kivy-APK
          path: bin/*.apk
