name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version

      - name: Install dependencies
        run: |
          sudo apt install -y python3 python3-pip build-essential git zip unzip wget
          pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Install Android SDK and Aidl
        run: |
          # تنزيل Android SDK Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          unzip commandlinetools-linux-10406996_latest.zip -d $HOME/Android/Sdk/cmdline-tools
          rm commandlinetools-linux-10406996_latest.zip
          
          # إعداد متغيرات البيئة
          echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> ~/.bashrc
          echo "export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> ~/.bashrc
          source ~/.bashrc

          # قبول التراخيص وتثبيت الأدوات باستخدام sdkmanager
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --update
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "ndk;21.4.7075529"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kivy-APK
          path: bin/*.apk
