name: Build Android APK from Python

on:
  push:
    branches:
      - main

jobs:
  upload_sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies (curl, unzip)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Download Android SDK Command Line Tools
        run: |
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools-linux.zip
          unzip commandlinetools-linux.zip
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          mv cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

      - name: Verify Android SDK is installed
        run: |
          ls -l $HOME/Android/Sdk/cmdline-tools/latest  # عرض محتويات المجلد للتأكد من أن الأدوات تم تحميلها

      - name: Upload Android SDK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-sdk
          path: $HOME/Android/Sdk  # رفع المجلد بالكامل

  build_apk:
    runs-on: ubuntu-latest
    needs: upload_sdk  # يعتمد على job "upload_sdk"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download Android SDK
        uses: actions/download-artifact@v3
        with:
          name: android-sdk

      - name: Verify Android SDK is downloaded
        run: |
          ls -l $HOME/Android/Sdk/cmdline-tools/latest  # عرض محتويات المجلد بعد تنزيله

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies (python3, build-essential, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential curl unzip

      - name: Install OpenJDK 8
        run: |
          sudo apt-get install -y openjdk-8-jdk

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Install Cython
        run: |
          pip install cython

      - name: Set up Android SDK
        run: |
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/build-tools/30.0.3:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK dependencies
        run: |
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-29" "system-images;android-29;google_apis;x86_64"

      - name: Build APK with Buildozer
        run: |
          cd .  # أو المسار الصحيح لمشروعك
          buildozer android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-android-apk
          path: bin/*.apk
