name: Build Android APK from Python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (python3, build-essential, etc.)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential

    - name: Install OpenJDK 8
      run: |
        sudo apt-get install -y openjdk-8-jdk

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Install Cython
      run: |
        pip install cython

    - name: Install Android SDK and AIDL
      run: |
        sudo apt-get install -y android-sdk
        sudo apt-get install -y android-sdk-platform-tools
        sudo apt-get install -y android-sdk-build-tools
        sudo apt-get install -y android-sdk-tools
        sudo apt-get install -y android-sdk-extra-tools

    - name: Build APK with Buildozer
      run: |
        cd .  # أو المسار الصحيح لمشروعك
        buildozer android debug

    - name: Upload APK as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-android-apk
        path: bin/*.apk

