name: Build Android APK from Python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (python3, build-essential, etc.)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential curl unzip

    - name: Install OpenJDK 8
      run: |
        sudo apt-get install -y openjdk-8-jdk

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Install Cython
      run: |
        pip install cython

    - name: Install Android SDK
      run: |
        # تحميل Android SDK Command Line Tools
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools-linux.zip
        unzip commandlinetools-linux.zip
        mkdir -p $HOME/Android/Sdk
        mv cmdline-tools $HOME/Android/Sdk/
        # إضافة Android SDK إلى البيئة
        echo "export ANDROID_HOME=$HOME/Android/Sdk" >> ~/.bashrc
        echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc
        # تثبيت الأدوات المطلوبة
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-29" "system-images;android-29;google_apis;x86_64"

    - name: Build APK with Buildozer
      run: |
        cd .  # أو المسار الصحيح لمشروعك
        buildozer android debug

    - name: Upload APK as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-android-apk
        path: bin/*.apk
