name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # استخدام بيئة ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip build-essential git zip unzip openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer
          pip install cython  # تثبيت Cython
          
      - name: Install Android SDK and AIDL
        run: |
          sudo apt-get install -y android-sdk
          echo "y" | sdkmanager --update  # تحديث SDK Manager
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          sdkmanager "extras;google;m2repository" "extras;android;m2repository" "extras;google;google_play_services"
          sdkmanager "ndk;21.4.7075529"  # تثبيت أدوات AIDL و NDK

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kivy-APK
          path: bin/*.apk
