name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تنزيل الكود
        uses: actions/checkout@v3

      - name: إعداد Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: إعداد Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0
          ndk: '22.1.7171670'

      - name: جعل gradlew قابلاً للتنفيذ
        run: chmod +x ./gradlew

      - name: بناء APK
        run: workflows/gradlew assembleRelease

      - name: رفع ملف APK
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: app/build/outputs/apk/release/app-release.apk
