# GitHub Action to Build Kivy App to APK

name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install kivy
          pip install buildozer

      - name: Build APK
        run: |
          buildozer init
          buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: myapp.apk
          path: bin/*.apk

